version: "3"

includes:
  api:
    taskfile: ./api/taskfile.yaml
    dir: ./api
  web:
    taskfile: ./web/taskfile.yaml
    dir: ./web
  infra: 
    taskfile: ./infrastructure/taskfile.yaml
    dir: ./infrastructure
