apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: opentelemetry-collector
spec:
  project: default
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.141.0
    helm:
      releaseName: opentelemetry-collector
      values: |
        config:
          receivers:
            prometheus:
              config:
                scrape_configs:
                  - job_name: app-metrics
                    metrics_path: /metrics
                    static_configs:
                      - targets:
                          - app-frontend-service.default.svc.cluster.local:4138
                          - app-backend-service.default.svc.cluster.local:3000

          exporters:
            prometheus:
              endpoint: "0.0.0.0:9464"

          service:
            pipelines:
              metrics:
                receivers:
                  - prometheus
                exporters:
                  - prometheus

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  revisionHistoryLimit: 10