version: "3"

tasks:
  run:
    dotenv: [.env]
    cmds:
      - go run .

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -v ./...

  generateEnv:
    cmds:
      - touch .env
      - truncate -s 0 .env
      - echo "HOST=localhost" >> .env
      - echo "PORT=3000" >> .env
      - echo "JWT_KEY=$(openssl rand -base64 32)" >> .env

  generateJWT:
    dotenv: [.env]
    silent: true
    preconditions:
      - openssl version
    cmds:
      - |
        jwt_header=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 | sed s/\+/-/g | sed 's/\//_/g' | sed -E s/=+$//)
        payload=$(echo -n '{"sub":"arthur.dent"}' | base64 | sed s/\+/-/g |sed 's/\//_/g' |  sed -E s/=+$//)
        secret=$(echo $JWT_KEY)
        hexsecret=$(echo -n "$secret" | xxd -p | tr -d '\n')
        hmac_signature=$(echo -n "${jwt_header}.${payload}" | openssl dgst -sha256 -mac HMAC -macopt hexkey:$hexsecret -binary | base64  | sed s/\+/-/g | sed 's/\//_/g' | sed -E s/=+$//)
        echo "${jwt_header}.${payload}.${hmac_signature}"
