name: CD
on:
  push:
    tags:
      - "*.*.*" # release tags like 1.2.3
  workflow_dispatch:

env:
  RC_TAG_API: api:${{ github.ref_name }}-rc
  RC_TAG_WEB: web:${{ github.ref_name }}-rc

jobs:
  docker:
    name: Build, Scan & Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate JWT Token
        id: genjwt
        working-directory: ./api
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: |
          ACCESS_TOKEN=$(task generate:jwt)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: "Build Docker Image (API)"
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          load: true # load image into actions docker context for later use in pipeline
          build-args: |
            JWT_KEY=${{ secrets.JWT_KEY }}
          tags: ${{ env.RC_TAG_API }}

      - name: "Build Docker Image (Web)"
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          load: true # load image into actions docker context for later use in pipeline
          build-args: |
            ACCESS_TOKEN=${{ env.ACCESS_TOKEN }}
            API_BASE_URL=${{ vars.API_BASE_URL }}
          tags: ${{ env.RC_TAG_WEB }}

      # action does not rebuild the image - cache from the previous build step is used
      - name: "Push Image (API)"
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          build-args: |
            JWT_KEY=${{ secrets.JWT_KEY }}
          tags: |
            ghcr.io/${{ github.repository }}/api:latest

      # action does not rebuild the image - cache from the previous build step is used
      - name: "Push Image (Web)"
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          build-args: |
            ACCESS_TOKEN=${{ env.ACCESS_TOKEN }}
            API_BASE_URL=${{ vars.API_BASE_URL }}
          tags: |
            ghcr.io/${{ github.repository }}/web:latest
