name: CI API
on:
  push:
    branches: [main]
    paths: [api/*]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build-api.yaml

  lint:
    uses: ./.github/workflows/lint-api.yaml
    needs: [build]

  test:
    uses: ./.github/workflows/test-api.yaml
    needs: [build]
