name: Test API
on:
  workflow_call:

jobs:
  test-unit:
    name: Test (Unit)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
      - name: Test
        working-directory: api
        run: go test -v ./...

  test-e2e:
    name: Test (E2E)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
      - name: Test
        working-directory: api
        run: go test -v -tags e2e ./tests/e2e/...
